"""
Preprocessing helper for src/foam/foam_flow.cpp (LBfoam free-surface solver).

FoamSimulation mirrors LattEasySimulation's shape (sims/<name>_<i>/ folder,
run_sim() through the same MPI helpers) but is a separate class: foam_flow
has a different XML schema, reads an existing ASCII geometry .dat
(0=pore, 1=wall, 2=matrix) instead of the binary int16 file that
create_geom_edist() writes, and returns a log path, not a permeability.

Cold start only: run_sim() always runs `foam_flow <xml>` with no second
argument. A second argument would make foam_flow restart from a checkpoint.

No nucleation: Nucleation/distribution is set to "none". foam_flow.cpp only
acts on "random", "one" and "list"; any other value leaves nucleiCenters
empty, so nucleateBubbles() is a no-op and no nucleation files are read.
The <Nucleation> block must still be present because the C++ reads
radius/shift/packingOffset/numberOfBubbles unconditionally.
"""

import os
import sys
import time
from pathlib import Path
from subprocess import PIPE, STDOUT, Popen as subprocess_popen

from latteasy._native import build_runtime_env, find_mpi_launcher, find_solver_executable

FOAM_EXE_CANDIDATES = [
    "src/foam/foam_flow",
    "build/src/foam/foam_flow",
    "bin/foam_flow",
]


def get_foam_executable(explicit=None, search_root=None):
    """Locate the compiled ``foam_flow`` binary (expected at src/foam/foam_flow).

    Order: explicit path, then latteasy._native.find_solver_executable()
    (called with no argument, as LattEasySimulation does) if it resolves to a
    file named ``foam_flow``, then a search under the repo root.
    """
    if explicit is not None:
        p = Path(explicit).resolve()
        if not p.is_file():
            raise FileNotFoundError(f"foam_flow executable not found: {p}")
        return p

    try:
        found = Path(find_solver_executable()).resolve()
        if found.name == "foam_flow" and found.is_file():
            return found
    except (FileNotFoundError, TypeError):
        pass

    root = Path(search_root) if search_root else Path(__file__).resolve().parents[2]
    for c in FOAM_EXE_CANDIDATES:
        p = root / c
        if p.is_file() and os.access(p, os.X_OK):
            return p.resolve()
    raise FileNotFoundError(
        "foam_flow executable not found. Build it, or pass solver_path=.../foam_flow. "
        f"Searched under {root}: {FOAM_EXE_CANDIDATES}"
    )


def create_folder(folder_name):
    try:
        os.mkdir(folder_name)
    except FileExistsError:
        pass


def _fmt(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return repr(v)
    return str(v)


def render_foam_xml(params):
    """params: {section: {key: value | {key: value}}} -> foam_flow XML text."""
    lines = ['<?xml version="1.0" ?>', "", "<!-- generated by FoamSimulation -->"]
    for section, body in params.items():
        lines.append(f"<{section}>")
        for k, v in body.items():
            if isinstance(v, dict):
                lines.append(f"    <{k}>")
                for k2, v2 in v.items():
                    lines.append(f"        <{k2}> {_fmt(v2)} </{k2}>")
                lines.append(f"    </{k}>")
            else:
                lines.append(f"    <{k}> {_fmt(v)} </{k}>")
        lines.append(f"</{section}>")
        lines.append("")
    return "\n".join(lines) + "\n"


class FoamSimulation:
    """Set up and cold-start a foam_flow simulation without nucleation."""

    # Values follow examples/foam_flow/rough_restart.xml.
    DEFAULT_PARAMS = {
        "geometry": {
            "fluidPoolHeight_LB": 50,
        },
        "Nucleation": {
            # "none" -> no seeding branch runs in foam_flow.cpp.
            "distribution": "none",
            "numberOfBubbles": 0,
            "shift": 20,
            "radius": 12,
            "packingOffset": 3,
        },
        "fluid": {
            "rho_LB": 1.0,
            "R_s": 1,
            "p_ini": 0.33,
            "temperature": 1,
            "tau_LB": 0.95,
            "sigma_LB": 5.0e-3,
            "contactAngle": -1.0,
            "tauD_LB": 0.53,
            "gasIni_LB": 0.0,
            "kh_LB": 1.0e-5,
            "pi_LB": 0.032,
            "source_LB": 0.0,
            "surfaceDiffusion": False,
        },
        "numerics": {
            "gravity": True,
            "g_LB": -5.0e-5,
            "maxIter": 130000,
            "cSmago": 0.0,
            "freezeLargestBubble": False,
            "bubbleVolumeRatio": 1.0,
            "alpha": -1.0,
            "beta": -1.0,
        },
        "output": {
            "statIter": 100,
            "outIter": 500,
            "save_sim": False,
            "save_it": 10000,
            "restart_it": 0,
        },
    }

    def __init__(self, geom_path, domain_size, params=None, cpus=4,
                 solver_path=None, name="foam", mpi_launcher=None):
        """
        Parameters
        ----------
        geom_path : str or Path
            ASCII geometry .dat (0=pore, 1=wall, 2=matrix).
        domain_size : (nx, ny, nz)
            Must match the geometry file.
        params : dict, optional
            Nested overrides merged onto DEFAULT_PARAMS.
        cpus : int
        solver_path : str or Path, optional
            Explicit foam_flow binary; otherwise searched for.
        name : str
            Prefix for the xml file and the sims/ subfolder.
        mpi_launcher : str, optional
            MPI launcher to use, e.g. "ibrun" on TACC. Defaults to whatever
            latteasy._native.find_mpi_launcher() returns (mpirun/mpiexec).
            ibrun only works inside a Slurm allocation (sbatch or idev).
        """
        self.geom_path = Path(geom_path).resolve()
        if not self.geom_path.is_file():
            raise FileNotFoundError(f"geometry file not found: {self.geom_path}")

        self.nx, self.ny, self.nz = domain_size
        self.name = name
        self.cpus = cpus
        self.mpi_launcher = mpi_launcher
        self.lbm_loc = str(get_foam_executable(solver_path))

        self.params = {k: dict(v) for k, v in self.DEFAULT_PARAMS.items()}
        for section, body in (params or {}).items():
            self.params.setdefault(section, {}).update(body)

        create_folder("sims")
        self.folder_num = self._create_new_folder()
        self.folder_path = f"sims/{name}_{self.folder_num}"
        self.out_path = f"{self.folder_path}/out"
        create_folder(self.out_path)

        # foam_flow.cpp concatenates outDir + "filename" directly, so outDir
        # must exist and end with "/". geomName is opened as given, so pass an
        # absolute path (the solver runs with cwd = the sims folder).
        self.params["geometry"]["simulationDomain"] = {
            "nx": self.nx, "ny": self.ny, "nz": self.nz,
        }
        self.params["geometry"]["geomName"] = str(self.geom_path)
        self.params["output"]["outDir"] = str(Path(self.out_path).resolve()) + "/"

        self.xml_path = f"{self.folder_path}/{self.name}.xml"
        with open(self.xml_path, "w") as f:
            f.write(render_foam_xml(self.params))

    def _create_new_folder(self):
        for i in range(10_000_000_000):
            try:
                os.mkdir(f"sims/{self.name}_{i}")
                break
            except FileExistsError:
                continue
        return i

    def run_sim(self, mpi_procs=None):
        """Cold-start the solver. Returns the path of out/bubbleTimeHistory.log."""
        explicit_procs = mpi_procs is not None
        if mpi_procs is None:
            mpi_procs = self.cpus

        mpi_launcher = self.mpi_launcher or find_mpi_launcher()
        if mpi_launcher is None:
            raise RuntimeError(
                "No MPI launcher was found. Install MPI and make sure `mpirun` or `mpiexec` is on your PATH."
            )

        # One argument after the binary -> cold start.
        if os.path.basename(str(mpi_launcher)) == "ibrun":
            # TACC's ibrun takes its task count from the Slurm allocation
            # (sbatch -n / idev -n). Only pass -n if the caller explicitly
            # asked for a count; it must not exceed the allocation.
            cmd = [mpi_launcher]
            if explicit_procs:
                cmd += ["-n", str(mpi_procs)]
            cmd += [str(self.lbm_loc), f"{self.name}.xml"]
        else:
            cmd = [mpi_launcher, "-n", str(mpi_procs), str(self.lbm_loc), f"{self.name}.xml"]
        print(f"Running (cwd={self.folder_path}):", " ".join(cmd))

        # cwd = sims folder: saveState() writes continue.xml/checkpoint_* to
        # the CWD, not to outDir.
        run_log = os.path.join(self.folder_path, "run.log")
        env = build_runtime_env()
        t0 = time.time()
        # Stream solver output to the terminal and to run.log at the same time.
        # stderr is merged into stdout; the log is flushed line by line, so
        # `tail -f run.log` from another terminal also works.
        with open(run_log, "w") as fh:
            proc = subprocess_popen(
                cmd, cwd=self.folder_path, env=env,
                stdout=PIPE, stderr=STDOUT, text=True, bufsize=1,
            )
            try:
                for line in proc.stdout:
                    sys.stdout.write(line)
                    sys.stdout.flush()
                    fh.write(line)
                    fh.flush()
                returncode = proc.wait()
            except KeyboardInterrupt:
                proc.terminate()
                proc.wait()
                raise
        dt = time.time() - t0

        if returncode != 0:
            raise RuntimeError(f"Simulation failed (exit {returncode}). Check `{run_log}`.")

        history_log = os.path.join(self.out_path, "bubbleTimeHistory.log")
        print(f"Finished in {dt / 60:.1f} min.")
        return history_log
